### ISSUE TITLE
Visibility is low due to name conflicting boost-mpl.

### ISSUE THREAD

**Issue by acdemiralp** [rabauke/mpl#11]
Hello,

this is probably the most up to date MPI C++ interface, but finding it among hundreds of other libraries were impossible until you mentioned it in the MPI forum. This is because MPL is a very common abbreviation and even has correspondents in C++. Do you have any plans to change this?

While I'm at it; do you have any plans to support the vcpkg build system https://github.com/microsoft/vcpkg which is the de-facto standard package manager for C++?

**Comment by rabauke** [comment]
Hi, 
currently there is no plan to rename the library. May be I should think about it. There was actually another [Message Passing Library](https://www.phy.ornl.gov/csep/SP2_guide/node12.html) by IBM in the 1990s.

Regarding vcpkg, I am not familiar with this package manager. 
* Is it actually commonly used (outside the Microsoft ecosystem)? 
* What about [hunter](https://hunter.readthedocs.io/en/latest/) or [conan](https://conan.io/) or even [nuget](https://devblogs.microsoft.com/cppblog/nuget-for-c/)?
* What do you precisely mean by supporting vcpkg? Does this require to tweak MPL in any way or do you want to suggest to [contribute MPL as a new library to vcpkg](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019#contribute-new-libraries)?

**Comment by VictorEijkhout** [comment]
What MPI forum was that?

**Comment by rabauke** [comment]
@VictorEijkhout The post by @acdemiralp refers to https://github.com/mpi-forum/mpi-issues/issues/288 .

**Comment by jacobmerson** [comment]
I just found this package (through the same MPI forum thread that @acdemiralp mentioned). I'm surprised I haven't seen this library until now since it looks really nice! The library is impossible to find if you search for `mpl`, but it's the first result when searching form `mpl mpi` so maybe it's reasonable.

Currently, I think `spack` is the go-to package manager for hpc folks. When I get some spare time to play around with `mpl` I can contribute the `spack` package. However, I think this will require some modification to the `mpl cmake` scripts to include the headers as an interface library. I will try to submit a PR when I have some free time.

**Comment by rabauke** [comment]
@jacobmerson Thanks for your feedback. Pull requests are always welcome.

**Comment by rabauke** [comment]
I am closing this. I think it is actually possible to find this library by querying common search engines and using suitable search key words. Furthermore, MPL has been made available via the Spack package manager, see https://github.com/spack/spack/pull/26522.
