### ISSUE TITLE
Operations on C-style arrays

### ISSUE THREAD

**Issue by VictorEijkhout** [rabauke/mpl#14]
It is possible to send a 

```
float x[2][3][4]
```

with an `mpl::communcator::send` without using the `contiguous_layout`. However, my attempt to do a `reduce` on such an array failed. 

```
  float rank2p2p1[2] = { 2*xrank,2*xrank+1 };
  comm_world.allreduce(mpl::plus<float>(), rank2p2p1);
```

Is there something in the design of operators that prevents this?

**Comment by rabauke** [comment]
The type that is returned by the reduction operator must match the type of the 2nd argument to `allreduce`. Thus you have to replace `float` by the array type of your example above. This, however, is change not sufficient because C arrays are not normal data types with a proper value semantics (array to pointer decay, C arrays can not be used as function return values). Therefore,
`mpl::plus`, which is defined as
```
template<typename T>
  struct plus {
    T operator()(const T &x, const T &y) const { return x + y; }
  };
```
cannot be applied to arrays. If you would like to avoid using `mpl::contiguous_layout` (which is certainly a good thing) you have to wrap the array into a struct or class type, which has value semantics and can be used as as return type. See `collective.cc` in the examples directory for an example.
