### ISSUE TITLE
Can API changes be more clearly marked?

### ISSUE THREAD

**Issue by VictorEijkhout** [rabauke/mpl#21]
I notice that 

```
std::communicator::split
```

has been renamed 

```
std::communicator::split_tag
```

and the identifier `split` is not an object, rather than a class.

How can I be apprised of such API changes?

**Comment by rabauke** [comment]
I am sorry, when this change has raised some inconveniences on your side. MPL is a library under development. There had been several smaller breaking changes recently. Some of them are related to the fact that I no longer restrict MPL to C++11. All major C++ compiler support C++17 since quite a while, which allows for a nicer syntax in MPL here and there.

In stead of
```C++
mpl::communicator comm_new{mpl::communicator::split(), comm_world, rank % 2 == 0};
```
the following code can be used now
```C++
mpl::communicator comm_new{mpl::communicator::split, comm_world, rank % 2 == 0};
```
This was not possible before C++17, at least not with a header-only library.

Currently, I am completing the doxygen documentation for all existing classes. The documentation is somewhat basic and possibly not sufficient for developers without an MPI background. But at least, there will be _some_ documentation for all classes. At the same time I am also reviewing and improving the code. When the documentation has been completed there will be a 0.1 release. Starting from this release, api changes will be documented more clearly in release notes of each new release. API stability is has not absolute priority before we have reached version 1.0.

Furthermore, I have prepared a pull request to incorporate MPL into [Spack](https://spack.readthedocs.io). This pull request, however, will not be opened before version 0.1. Until version 0.1, I will try to remove possible api inconsistencies in order to reduce the likelihood of breaking api changes after version 0.1.
